### ISSUE TITLE
create-symlinks command links to absolute path

### ISSUE THREAD

**Issue by JayAndCatchFire** [ImmoweltGroup/flow-mono-cli#147]
I was surprised to find that the `flow-mono create-symlinks` command creates symlinks to the absolute path of the root `.flowconfig` file.  The source code makes it obvious that it's the intended action.

The potential problem with this is that the symlinks are then only guaranteed to be valid on the original filesystem on which they were created.  They'll break on anyone else's computer.

Does that mean that the intention is for these symlinks to _not_ be checked into a git repo?  Are they supposed to be created semi-manually whenever someone clones the repo?

**Comment by Inkdpixels** [comment]
Hey @JayAndCatchFire - The symlinks are indeed not intended to be committed to git. This is a common best practice since the flow-typed definitions itself are dependencies and thus should not be committed.

We know that this is recommended by flow-typed itself, but it embraces a bad practice and suspends fixing the root issues, also see https://github.com/flow-typed/flow-typed/issues/1494 for reference and more info on that topic.

If this answers your question please close the issue, thanks :) :+1:
